version: "3.3"
services:
  api:
    build: .
    environment:
      - DISCORD_TOKEN=OTY3NTI0OTM2NTUxODk1MDUx.YmRj0A.Qgn849DFxCQpC2evCr2MB_suQ3A
      - GUILD_ID=839425986817818654
      - CLIENT_ID=967524936551895051
      - COGNITO_USERPOOL_ID=eu-central-1_IbWSTtlMK
      - COGNITO_CLIENT_ID=4hv808r649t602m0d0ve8pba17
      - DEBUG=kampus-bot*
    ports:
      - "3000:3000"
  deploycmds:
    build: .
    entrypoint: node ./deploy-commands.js
    environment:
      - DISCORD_TOKEN=OTY3NTI0OTM2NTUxODk1MDUx.YmRj0A.Qgn849DFxCQpC2evCr2MB_suQ3A
      # - GUILD_ID=504590280675295233
      - GUILD_ID=839425986817818654
      - CLIENT_ID=967524936551895051
      - COGNITO_USERPOOL_ID=eu-central-1_IbWSTtlMK
      - COGNITO_CLIENT_ID=4hv808r649t602m0d0ve8pba17
      - DEBUG=kampus-bot*

