# fly.toml app configuration file generated for kampus-discord-bot on 2023-11-26T10:45:21-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kampus-discord-bot"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
